# Generated by Django 2.0.1 on 2018-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Название')),
                ('source', models.CharField(max_length=250, verbose_name='Источник')),
                ('link_hash', models.CharField(max_length=250, unique=True, verbose_name='Хеш')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('refer_count', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
            ],
        ),
    ]
