# Generated by Django 2.0.1 on 2018-02-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_hash',
            field=models.CharField(editable=False, max_length=250, unique=True, verbose_name='Хеш'),
        ),
        migrations.AlterField(
            model_name='link',
            name='source',
            field=models.URLField(max_length=250, verbose_name='Источник'),
        ),
    ]
